import { Metadata } from 'next'

import { BoardView } from '@/views'

export const metadata: Metadata = {
  title: 'Kandan app',
  description: 'Generated by create next app',
}

export default function Home() {
  return <BoardView />
}
